ALTER TABLE email_notifications DROP CONSTRAINT IF EXISTS chk_email_type;

ALTER TABLE email_notifications ADD CONSTRAINT chk_email_type CHECK (notification_type IN (
    'DAILY_REPORT', 'ABSENCE_ALERT', 'LATE_ALERT', 'WELCOME', 'RFID_ASSIGNED',
    'LOGIN_OTP', 'WELCOME_USER', 'PASSWORD_FIRST_SETUP', 'PASSWORD_RESET',
    'NEW_EMPLOYEE_LEADER_NOTICE', 'ANNOUNCEMENT'
));
